In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('spam.csv' , encoding='latin-1')[['v1' , 'v2']]
df.columns = ['label' , 'message']

In [4]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting click (from nltk)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: joblib in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 13.2 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp311-cp311-win_amd64.whl (274 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.8 nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1

In [10]:
import string
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yashw\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [13]:
def clean_text(text):
   
    text = text.lower()

    
    text = ''.join([c for c in text if c not in string.punctuation])

   
    words = text.split()
    words = [word for word in words if word not in stopwords.words('english')]

    
    return ' '.join(words)

In [14]:
df['cleaned'] = df['message'].apply(clean_text)
df[['message' , 'cleaned']].head()

,message,cleaned
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,"Nah I don't think he goes to usf, he lives aro...",nah dont think goes usf lives around though

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['cleaned'])
y = df['label']

In [19]:
X.shape

(5572, 9376)

In [20]:
from sklearn.model_selection import train_test_split
X_train , X_test  , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)
X_train.shape , X_test.shape

((4457, 9376), (1115, 9376))

In [21]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [22]:
model.fit(X_train , y_train)

MultinomialNB()

In [23]:
y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
accuracy  = accuracy_score(y_test , y_pred)
conf_matrix = confusion_matrix(y_test , y_pred)
class_report = classification_report(y_test , y_pred)

In [25]:
print("accuracy:" , accuracy)
print("confusion matrix:" , conf_matrix)
print("classification report:" , class_report)

accuracy: 0.9659192825112107
confusion matrix: [[965   0]
 [ 38 112]]
classification report:               precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.75      0.85       150

    accuracy                           0.97      1115
   macro avg       0.98      0.87      0.92      1115
weighted avg       0.97      0.97      0.96      1115

In [26]:
import pickle

In [27]:
pickle.dump(model , open('spam_model.pkl' , 'wb'))
pickle.dump(tfidf , open('vectorizer.pkl' , 'wb'))

In [28]:
def predict_spam(message):
    cleaned_message = clean_text(message)

    transformed_message = tfidf.transform([cleaned_message])

    prediction = model.predict(transformed_message)

    return prediction[0]

In [38]:
new_message = "Congratulations! You won a $1000 gift card."
result = predict_spam(new_message)

if result == "spam":
    print("message is spam")
else:
    print("message is ham")

message is ham

In [37]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (1.44.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging<25,>=20 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (5.28.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (19.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from altair<6,>=4.0->streamlit) (1.34.1)
Requirement already satisfied: colorama in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.20.1)
Requirement already satisfied: six>=1.5 in c:\users\yashw\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)